
name: "Create Default Labels"

on:
  push:
    paths:
      - ".github/workflows/labels.yml"

jobs:
  label-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Label Sync
        uses: EndBug/label-sync@v2
        with:
          config-file: labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.LABEL_SYNC_TOKEN }}
